server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://47.94.81.15:3306/search?useUnicode=true&amp;characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: cat
    password: cat123
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      validation-query: SELECT 1

  jackson:
    joda-date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    static-path-pattern: /img/**
  resources:
    static-locations: file:/home/soft/apache-tomcat-8.5.38/webapps/server/upload
mybatis:
  type-aliases-package: com.server.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

oss:
  endpoint: http://oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAIHCf3hVCA6Q2t
  accessKeySecret: s1bvMaXympvvarrcIZtrm61yV6HZKc
  bucketName: vedio-test1